### ISSUE TITLE
conflict with white(s)/0 from dcg/basics

### ISSUE THREAD

**Issue by step21** [fnogatz/dcg4pt#1]
Hey,

thank you for your work. I wanted to use it, but also had used some things, such as `whites/0` from dcg/basics.
This seems to result in an error that suggests that only the normal (unexpanded) whites/2 is available, but also says that I had used whites/3 (expanded) when in fact I had not. Is there a solution to this without redefining whites/0?

**Comment by fnogatz** [comment]
Hm, not sure if I can follow. Could you provide a minimal example with the error message you are experiencing? *dcg4pt* itself does not implement a predicate `white` the library(dcg/basics)) could conflict with.

**Comment by step21** [comment]
My most likely explanation would be that the whites/0 from dcg/basics does get 'called' with /3 but is not properly expanded (so is still a /2). If not, then I might have done sth else wrong. I will try to provide a minimal working example tomorrow.

**Comment by step21** [comment]
Closing b/c old and I also cannot replicate it anymore. Apologies.
